### ISSUE TITLE
Use `jasmine-expect` in `beforeAll` without `describe` will throw exception

### ISSUE THREAD

**Issue by freewind** [JamieMason/Jasmine-Matchers#106]
Test code:

```
import 'jasmine-expect';

beforeAll(() => {
  expect('hello').toBeSameLengthAs("abcde");
});

describe("A suite", function () {
  it("contains spec with an expectation", function () {
    expect('hello').toBeSameLengthAs("abcde");
  });
});
```
will throw:

```
Suite error: undefined
  Message:
    TypeError: expect(...).toBeSameLengthAs is not a function
  Stack:
        at <Jasmine>
        at UserContext.beforeAll (/dev/typescript--jasmine-expect--before-all-issue-demo/spec/hello-spec.ts:4:19)
        at <Jasmine>
        at runCallback (timers.js:781:20)
        at tryOnImmediate (timers.js:743:5)
```

A complete minimal demo: https://github.com/freewind-demos/typescript--jasmine-expect--before-all-issue-demo

**Comment by JamieMason** [comment]
Jasmine and Jest both require that `expect` calls are only within `it` or `test` blocks 👍
